version: '3'
services:
  t6_wbp_apache:
    container_name: hms_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/www
    ports:
      - 80:80
  hms_mysql:
    container_name: hms_mysql8
    image: mysql:8.0
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
#    volumes:
#      - ./database/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_USER: 'root'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
  hms_phpmyadmin:
    container_name: hms_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    environment:
      PMA_HOST: hms_mysql
    depends_on:
      - hms_mysql